### PR TITLE
Changes world map pin desc/caption, adds imgui.ini to the ignore

### PR DESCRIPTION
**Pull request by ComradeCheekiBreeki**
Changes world map pin caption to just "Rivia" since enough of the region is included to make sense in my opinion, and also I think it's shorter and catchier. Changes description to something a bit more flowery, definitely not my best work but I figured I might as well take a stab at it anyway.

Also adds imgui.ini to the gitignore, since it's going to change between users and depending on how the quest takes shape

### CODE REVIEW

**Comment by Damastyr** [comment]
Regarding the name - Rivia Capital was initially chosen as name because it's not entire Rivia, but only the region around its capital. Same for Novigrad and Wyzima not being called "Redania" or "Temeria". That was the initial logic. So what do you think, should this old name stay?

**Comment by ComradeCheekiBreeki** [comment]
I'm kind of torn on this now that you say that- my reasoning was that Velen, despite being at least a fifth of the size of the actual Velen region and not even containing Gors Velen in game, would be consistent with this, but it's true the other way around as well. So I think it really could be either one. Personally I think Rivia is shorter and catchier, but if we wanted to emphasize the "city" aspect City of Rivia could work as well, though it might be a bit long (even though I like how that sounds and looks on the map)

**Comment by Damastyr** [comment]
If being catchy and short is the goal, while in the same time, keeping geographical consistensy in mind - perhaps "Loc Escalott" would be another option. Rivia is too generalizing, City of Rivia or Rivia Capital are too long, and Rivia City is unfitting if you know what I mean.
Loc Escalott is the name of the lake which occupies almost a half of the hub. The only problem with this name is that it's a lake after all, not a city/fortress/duchy. But it still could be associated with the place as a recognizable mark.

**Comment by ComradeCheekiBreeki** [comment]
This is why I'm wary to chose Loc Escalott, since I feel like many players of TW3 won't know much about the books and other games and probably only know about Rivia from Geralt's name, so I think strong first impressions in terms of the Rivia-ness of the region are important. I think I vote City of Rivia, since many other locations have long names like "The Duchy of Toussaint" or "Royal Palace in Vizima"

**Comment by Damastyr** [comment]
I think it is decided then. City of Rivia would be the caption. What about the description? I can't see it, how do I?

**Comment by ComradeCheekiBreeki** [comment]
Go to the "files changed" tab at the top of the pull request and it should have a list of all the files that were modified and how they were changed (green is line added, red is line removed, usually green line next to a red line means that line was changed)

**Comment by ComradeCheekiBreeki** [comment]
Updated the commit to be consistent with the Discord discussion, hopefully it should be ready to merge

**Pull request merged**
